#!/bin/sh
#
# buildpackage      Build a NOCC package for release
#
# Author:            Olivier Cahagne
#

if test $# -eq 0
then
  echo "Missing first parameter (name of package)"
  echo "Usage: buildpackage <name of package>"
  echo "Example: buildpackage nocc-0.9"
  exit 0
fi

distname=`echo "$1"`
myname=`basename \`pwd\`` 
cd .. && cp -rp $myname $distname
cd $distname
 rm -rf CVS/ buildpackage
 for i in docs img html lang 
   do
   cd $i
   rm -rf CVS/
   cd ..
   done;
cd ..
tar cf $distname.tar $distname
rm -f $distname.tar.*
bzip2 -9 $distname.tar
md5sum $distname.tar.bz2
sync; sleep 2
md5sum $distname.tar.bz2
bzip2 -t $distname.tar.bz2
echo creating zip archive
zip -rq9 $distname.zip $distname
md5sum $distname.zip
sync; sleep 2
md5sum $distname.zip
zip -T $distname.zip
rm -rf $distname
